general {
    # Comando para trancar a tela (chamado pelo loginctl lock-session)
    lock_cmd = pidof hyprlock || hyprlock
    
    # O que fazer ANTES de suspender (garante que tranque a tela)
    before_sleep_cmd = loginctl lock-session
    
    # O que fazer ao acordar (opcional, liga a tela se estiver desligada)
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Listener 1: Após 20 minutos (1200s), suspender o PC
listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
